In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [5]:
final_df = pd.read_csv("../data/processed/churn_processed.csv")
final_df.head()

,seniorcitizen,tenure,monthlycharges,gender_male,dependents_yes,phoneservice_yes,multiplelines_yes,internetservice_fiber optic,contract_one year,contract_two year,churn
0,0,1,25,0,0,0,0,0,0,0,1
1,0,41,25,1,0,1,0,0,1,0,0
2,0,52,19,0,1,1,0,0,0,0,0
3,0,1,76,0,0,1,0,0,1,0,1
4,0,67,51,1,0,1,0,1,0,0,0

In [6]:
X = final_df.drop("churn", axis=1)
y = final_df["churn"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [8]:
scale_cols = ["tenure", "monthlycharges"]
print("Columns to scale:", scale_cols)

Columns to scale: ['tenure', 'monthlycharges']

In [9]:
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

In [10]:
scaler = StandardScaler()

X_train_scaled[scale_cols] = scaler.fit_transform(X_train[scale_cols])
X_test_scaled[scale_cols] = scaler.transform(X_test[scale_cols])

In [11]:
X_train_scaled.head()

,seniorcitizen,tenure,monthlycharges,gender_male,dependents_yes,phoneservice_yes,multiplelines_yes,internetservice_fiber optic,contract_one year,contract_two year
3757,0,-1.276682,-0.149881,1,1,1,0,0,0,1
3165,0,-0.096089,-0.315125,0,0,1,0,0,1,0
4912,1,0.555273,1.172071,0,0,1,1,1,0,0
3877,0,0.433143,0.048412,1,0,1,0,0,1,0
3818,0,-1.276682,-1.471834,1,0,1,1,1,0,1

In [12]:
print("Before scaling:")
print(X_train[scale_cols].describe())

print("\nAfter scaling:")
print(X_train_scaled[scale_cols].describe())

Before scaling:
            tenure  monthlycharges
count  5634.000000     5634.000000
mean     32.360312       64.535144
std      24.566104       30.260956
min       0.000000       18.000000
25%       9.000000       35.000000
50%      29.000000       70.000000
75%      55.000000       90.000000
max      72.000000      119.000000

After scaling:
             tenure  monthlycharges
count  5.634000e+03    5.634000e+03
mean   1.292698e-16    2.106153e-16
std    1.000089e+00    1.000089e+00
min   -1.317392e+00   -1.537931e+00
25%   -9.510009e-01   -9.761015e-01
50%   -1.367987e-01    1.806070e-01
75%    9.216642e-01    8.415833e-01
max    1.613736e+00    1.799999e+00

In [13]:
train_scaled_df = X_train_scaled.copy()
train_scaled_df["churn"] = y_train

test_scaled_df = X_test_scaled.copy()
test_scaled_df["churn"] = y_test

In [14]:
train_scaled_df.to_csv("../data/processed/churn_train_scaled.csv", index=False)
test_scaled_df.to_csv("../data/processed/churn_test_scaled.csv", index=False)

print("Scaled train and test datasets saved successfully.")

Scaled train and test datasets saved successfully.